# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07775793ff292feab754604ef02b94e62b2bdd38a9d546a1a470c2c022da66f18814e99ce80f212341feb4d3e4c546badb6cd5fbbdcaa55a41f96752ec7a4cb5

test:
  secret_key_base: 26e6e360b81e9a36e0bf985ff079b6af16ec8c1a92eeb31815b54f7aca3c9b4dc45360af693d37c79eab2bd44a049eb31f29daee1b14f1bb08b36b185fe01238

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
